### PR TITLE
Update for Auth API V4

### PR DESCRIPTION
**Pull request by owohappy**
No responding with an User ID anymore, only the desired tokens

### CODE REVIEW

**Comment by owohappy** [comment]
Accidentally added a "]" back into it

**Comment by ahivert** [comment]
thanks @owohappy can you fix tests (at least for py3.10+)

**Comment by edwinvanderham** [comment]
Thanks for you quick response. I need some time before I can try this, I now use "pip install tgtg" so I need to do some changes to get it directly from github first

**Comment by owohappy** [comment]
@ahivert Can do, just give me a couple of minutes

**Comment by ahivert** [comment]
thanks a lot @owohappy merged and release 0.18.0 published

**Pull request merged**
